# Generated by Django 5.2.5 on 2025-08-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название волны')),
                ('max_capacity', models.IntegerField(verbose_name='Максимальное количество участников')),
                ('current_count', models.IntegerField(default=0, verbose_name='Текущее количество')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Волна мероприятия',
                'verbose_name_plural': 'Волны мероприятий',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('vk_link', models.URLField(blank=True, verbose_name='Ссылка на ВК')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Посетитель',
                'verbose_name_plural': 'Посетители',
            },
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('vk_link', models.URLField(blank=True, verbose_name='Ссылка на ВК')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Черный список',
                'verbose_name_plural': 'Черный список',
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
