# Generated by Django 5.2.5 on 2025-08-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_fix_blacklist_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
    ]
