# Generated by Django 5.2.5 on 2025-08-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_visitor_birth_date_visitor_gender_visitor_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='allergies',
            field=models.TextField(blank=True, null=True, verbose_name='Аллергия'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='faculty',
            field=models.CharField(max_length=200, null=True, verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='group',
            field=models.CharField(max_length=50, null=True, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='health_issues',
            field=models.TextField(blank=True, null=True, verbose_name='Проблемы по здоровью'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='program',
            field=models.CharField(max_length=200, null=True, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='transfer',
            field=models.CharField(choices=[('need', 'Нужен'), ('not_need', 'Не нужен')], max_length=10, null=True, verbose_name='Трансфер'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='university',
            field=models.CharField(max_length=200, null=True, verbose_name='ВУЗ'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='year',
            field=models.PositiveIntegerField(null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
    ]
