# Generated by Django 5.2.5 on 2025-08-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_visitor_allergies_visitor_faculty_visitor_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='faculty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='program',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='transfer',
            field=models.CharField(blank=True, choices=[('need', 'Нужен'), ('not_need', 'Не нужен')], max_length=10, null=True, verbose_name='Трансфер'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ВУЗ'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Курс'),
        ),
    ]
