# Generated by Django 5.2.5 on 2025-08-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_visitor_birth_date_alter_visitor_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='program',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ВУЗ'),
        ),
    ]
