# Generated by Django 5.2.5 on 2025-08-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_visitor_faculty_alter_visitor_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='group',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='health_issues',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='program',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='university',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='year',
        ),
    ]
