# Generated by Django 5.2.5 on 2025-08-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_remove_visitor_allergies_remove_visitor_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Аллергия'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='faculty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='health_issues',
            field=models.TextField(blank=True, verbose_name='Проблемы по здоровью'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='program',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='transfer',
            field=models.CharField(blank=True, choices=[('need', 'Нужен'), ('not_need', 'Не нужен')], max_length=10, null=True, verbose_name='Трансфер'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ВУЗ'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Курс'),
        ),
    ]
